name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  deriv_chart:
    path: ../
  vibration: ^1.4.0
  intl: ^0.16.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: <1.0.0
  flutter_deriv_api:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-api.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.16.1
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_intl:
  main_locale: en
  enabled: true
  class_name: ExampleLocalization
