name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  deriv_chart:
    path: ../
  vibration: ^1.7.4-nullsafety.0
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  pref: ^2.2.0
  flutter_deriv_api:
    git:
      url: git@github.com:mohammadt-fs/flutter-deriv-api.git
      ref: mohammad-t/migrate_flutter_version_2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  intl_utils: ^2.0.0
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_intl:
  main_locale: en
  enabled: true
  class_name: ExampleLocalization
