name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  deriv_chart:
    path: ../
  vibration: ^1.4.0
  flutter_deriv_api:
    git:
      url: git@github.com:raminvakili-fs/flutter-deriv-api.git
      ref: ramin/fix_subscription_manager

dev_dependencies:

flutter:
  uses-material-design: true