builders:

  arbBuilder:
    import: "package:deriv_chart/builder/builder.dart"
    builder_factories: ["arbBuilder"]
    build_extensions: {".txt": ["/../../lib/l10n/intl_en.arb"]}
    build_to: source
    auto_apply: root_package
    defaults:
      generate_for:
        include:
          - assets/strings.txt
